version: '3'
services:
  web:
    build: .
    expose:
    - 80
    ports:
    - 80:3001
#    volumes:
#      - /tmp/blocks/:/opt/node/data/blocks/
#      - /tmp/chainstate/:/opt/node/data/chainstate/
